### ISSUE TITLE
Cannot enumerate devices: avdevice_list_input_sources failed

### ISSUE THREAD

**Issue by ChristopheI** [vignetteapp/SeeShark#1]
Hi,

This project sounds like rocket ! :)

I try it on Win10 using "dshow" as DeviceInputFormat, unfortunately avdevice_list_input_sources  failed: it always return -40 (Function not implemented)

I used ffmeg libraries from here: https://www.gyan.dev/ffmpeg/builds/#release-builds
more specifically these one: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z

Using this command line works well: ffmpeg -f dshow -list_devices true -i dummy

It seems a restriction with "dshow" and ffmpeg. 
I found this page useful :  https://programmerall.com/article/4886862481/

**Comment by Speykious** [comment]
Thank you!

It seems that FFmpeg doesn't have a way to do this _yet_.

https://trac.ffmpeg.org/wiki/DirectShow#Howtoprogrammaticallyenumeratedevices

**Comment by Speykious** [comment]
> It seems a restriction with "dshow" and ffmpeg. 
> I found this page useful :  https://programmerall.com/article/4886862481/
> 

This looks like a really informative page, but it has the most broken English I've ever seen... I'm having a hard time understanding it 7_7'

**Comment by ChristopheI** [comment]
> This looks like a really informative page, but it has the most broken English I've ever seen... I'm having a hard time understanding it 7_7'
Yep ... I'm not so fluent too but a little better I hope :)

Another point: did you intend to provide also a library to manage input audio devices ?

**Comment by sr229** [comment]
> > This looks like a really informative page, but it has the most broken English I've ever seen... I'm having a hard time understanding it 7_7'
> 
> Yep ... I'm not so fluent too but a little better I hope :)
> 
> Another point: did you intend to provide also a library to manage input audio devices ?
> 

We do not have immediate plans at the moment to make a audio library as our use case does not have any use for it.

**Comment by Speykious** [comment]
> > This looks like a really informative page, but it has the most broken English I've ever seen... I'm having a hard time understanding it 7_7'
> 
> Yep ... I'm not so fluent too but a little better I hope :)
> 
> Another point: did you intend to provide also a library to manage input audio devices ?

This library is only intended for camera devices.

To give even more context, the reason I'm making this library is because previously we had to use OpenCV to get camera output in C#, and we've had lots of issues with it. FFmpeg works way better for this use-case  (...provided we can actually enumerate the devices lol).

**Comment by Speykious** [comment]
> > This looks like a really informative page, but it has the most broken English I've ever seen... I'm having a hard time understanding it 7_7'
> 
> Yep ... I'm not so fluent too but a little better I hope :)
> 
> Another point: did you intend to provide also a library to manage input audio devices ?

Oh! Did you write this article?

**Comment by ChristopheI** [comment]
> Oh! Did you write this article?

Not at all !

I tried already your library at the beginning of this week and I found this article useful to get the list of devices in "dshow" context. 

I'm just a beginner about ffmpeg so your library is very useful !

I understand that this library is focus on Camera only. But I miss something to manage them without the need to manage microphones too... Perhaps you have a specific case

**Comment by adryzz** [comment]
> Another point: did you intend to provide also a library to manage input audio devices ?

For playing sounds on audio devices you can use something like NAudio, as it targets .net standard 2.0, but there are others.

If what you need to do is manage the devices at an OS level, AudioSwitcher.AudioApi will do the trick, but it is Windows only and targets .net framework

**Comment by ChristopheI** [comment]
I'm looking for a multi-platform solution - and if possible more specifically Xamarin.Form ( so .Net MAUI later).

> For playing sounds on audio devices or microphone input you can use something like NAudio, as it targets .net standard 2.0, but there are others.

NAudio seems more Windows oriented.  For others platforms It should be necessary to implement IWavePlayer natively 

You didn't suggest me FFmpeg to manage audio devices. Do you think it's a bad idea ? Did you have any experiences about this ?

**Comment by Speykious** [comment]
Actually, I can suggest that. Though it is really hard to deal with given that there is next to no documentation for its C API... There are examples, function and struct descriptions, and that's about it.

**Comment by ChristopheI** [comment]
Thanks you all your inputs !

I'll try to make a library to manage input audio devices.

I already know that I wouldn't find such a funny name as SeeShark ;)

**Comment by Speykious** [comment]
Haha x')

Good luck finding a name then!

**Comment by Speykious** [comment]
@ChristopheI I still haven't tested it on Windows because I've had issues with my Windows VM, but I made an attempt at fixing this issue on [this latest commit](https://github.com/vignetteapp/SeeShark/commit/1ed1f2e7a5cbcb9c0e096e8f9c0e0e3a4dc69d34).
Though @adryzz is going to test it soon. You can also give it a try, can't refuse additional help :)

**Comment by Speykious** [comment]
After a few more commits, [5be2f282](https://github.com/vignetteapp/SeeShark/commit/5be2f2827e5add75e4522b35dfeedd2f664a40ee) fixed it! It has been tested and the `SeeShark.Example.Ascii` now works on Windows no problem.
I will thus close this issue.

Thow honestly I'm still worried about cameras that would have the same name, if that ever happens.

**Comment by ChristopheI** [comment]
I also tested successfully on my side. Congrats !
