### ISSUE TITLE
Choose Camera resolution and FPS

### ISSUE THREAD

**Issue by ChristopheI** [vignetteapp/SeeShark#12]
Hi,

Did you intend to add a way to choose Camera resolution and FPS ?

Thx

**Comment by Speykious** [comment]
We should probably add a way to change the FPS, yes.
As for the resolution, something you can do is to downscale the camera image frame upon receiving it using a `FrameConverter` that we provide.

**Comment by ChristopheI** [comment]
I see **FrameConverter** class can do the job to downscale but if the resolution is set on the device itself you can save some CPU :) 
And it assumes also that default resolution is always the highest one.

**Comment by Speykious** [comment]
Noted! I'll see what I can do.
The way I test things currently is with virtual cameras using OBS, since my laptop doesn't have a physical camera.
We usually discuss our projects on [our Discord server](https://discord.gg/Tz96ZdKjSA) if you're interested :)
