### ISSUE TITLE
Screen enumeration functions are not implemented in FFmpeg for `gdigrab` and `dshow` input formats

### ISSUE THREAD

**Issue by Speykious** [vignetteapp/SeeShark#18]
We'll have to do the same as we did for X11 on screen devices and for DShow on camera devices, and use an external library to enumerate them.
If we create a `Display` from these input formats though, the screen does get fetched properly (for example with the path value `desktop` for `gdigrab` [as per instructed on the FFmpeg documentation](https://ffmpeg.org/ffmpeg-devices.html#gdigrab)), so actually fetching the screen can still be handled by FFmpeg.

**Comment by ChristopheI** [comment]
I have some code for Windows in **gdigrab** context (no DShow)

But **path** value is not enough (path is always set to **desktop**). It's necessary to set options like this
``` cs
                inputFormat = "gdigrab";
                options = new Dictionary<string, string>()
                {
                    ["offset_x"] = rect.X.ToString(),
                    ["offset_y"] = rect.Y.ToString(),
                    ["video_size"] = $"{rect.Width.ToString()}X{rect.Height.ToString()}"
                };
```

So it's necessary first to allow this in existing code.
Could you do that ?

in **X11Grab** context it will be helpfull to allow this kind of parameters to allow to take only a part of the screen
``` cs
                inputFormat = "x11grab";
                //https://superuser.com/questions/1562228/how-to-specify-the-size-to-record-the-screen-with-ffmpeg
                options = new Dictionary<string, string>()
                {
                    ["video_size"] = $"{rect.Width.ToString()}X{rect.Height.ToString()}",
                    ["grab_x"] = rect.X.ToString(),
                    ["grab_y"] = rect.Y.ToString()
                };
```
**Note:** It will be great also to allow to set **framerate** too in those Dictionary object

**Comment by Speykious** [comment]
We now enumerate both `gdigrab` and `dshow`, so this issue is fixed!
