### ISSUE TITLE
Format of the AVFrame is lost when created from FrameConverter.Convert()

### ISSUE THREAD

**Issue by ChristopheI** [vignetteapp/SeeShark#19]
Little bug:
The format of the AVFRame is lost when created FrameConverter.Convert() is used.

It's necessary to store it in the default constructor like this:
```cs
dstFrame->linesize.UpdateFrom(dstLinesize);
dstFrame->format = (int)dstPF;  // <= This line is missing
```

**Comment by Speykious** [comment]
I'll investigate this. I thought I had made it correctly with all the constructors around
