### ISSUE TITLE
Access Violation, in GC if the camera is busy

### ISSUE THREAD

**Issue by lubagov** [vignetteapp/SeeShark#27]
Hello!
Seems i found some bug.
Envieronment:
Windows 10 21H2 19044.1826;
ffmpeg version n5.0.1-7-g7389a49fd3-20220706 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b);
Camera USB 2.0, ELP Sony IMX179 (3264x2448);
.NET 6.0
SeeShark 3.1.0 (from nuget package)
First make camera busy, for example open https://webcamtests.com

Next run code:
```
// See https://aka.ms/new-console-template for more information
using FFmpeg.AutoGen;
using SeeShark;
using SeeShark.Device;
using SeeShark.FFmpeg;

Console.WriteLine("Hello, World!");

FFmpegManager.SetupFFmpeg(@"C:\ffmpeg\v5.0_x64\", "/usr/lib");

(int, int)? videoSize = (640,480);
try
{
    Camera camera;
    using (CameraManager manager = new CameraManager())
    {
        camera = manager.GetDevice(0,
            new VideoInputOptions
            {
                InputFormat = null,
                Framerate = new AVRational
                {
                    num = (int)30,
                    den = 1,
                },
                VideoSize = videoSize,
            }
        );
        Console.WriteLine($"Using camera {camera.Info}");
    }
}catch(Exception ex)
{
    Console.WriteLine($"cannot initialize camera {ex.Message}");
}
GC.Collect();
GC.WaitForPendingFinalizers(); //TODO if camera is busy, i crash here in  AccessViolation;
```
And now we crash on Access Violation in GC:
output:

```
Hello, World!
cannot initialize camera I/O error
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SeeShark.Decode.VideoStreamDecoder.DisposeUnmanaged()
   at SeeShark.Disposable.Finalize()

C:\Users\lubag\OneDrive\Documents\TestApp\TestSeeShark\TestSeeShark\bin\Debug\net6.0\TestSeeShark.exe (process 5872) exited with code -1073741819.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by Speykious** [comment]
I notice that you're not manually disposing the camera. `Camera` is an `IDisposable` object.
What happens if you call `camera.Dispose()` before your GC calls?

**Comment by lubagov** [comment]
I understand that the camera is busy, and it returned null. it couldn't open it.

**Comment by Speykious** [comment]
I tested this on Linux and couldn't reproduce. It might be specific to Windows.

**Comment by sr229** [comment]
> I tested this on Linux and couldn't reproduce. It might be specific to Windows.

I doubt this is platform specific considering our samples should also fail in Windows. This might be a user-induced issue and not our fault, but I could be wrong.

**Comment by lubagov** [comment]
[SeeShark\Decode\VideoStreamDecoder.cs:170](https://github.com/vignetteapp/SeeShark/blob/b3f41a5cb5a5295c28809dfbba01b44cbb9792a8/SeeShark/Decode/VideoStreamDecoder.cs#L170) AccessViolation.
in
`ffmpeg.avformat_close_input(&formatContext);`

Here as I understand, that IO / Error was on line 55:
```
ffmpeg.avformat_open_input(&formatContext, url, inputFormat, &dict).ThrowExceptionIfError();
```
Accordingly, an attempt to close something that has not been opened leads to an error.

**Comment by Speykious** [comment]
Oh, I see. I'll fix that on the PR then.

Also don't hesitate to comment on the PR instead, since you can review code directly which makes it easier to point out where the bug actually lies. :)

**Comment by Speykious** [comment]
> Accordingly, an attempt to close something that has not been opened leads to an error.

I now made it so that it doesn't close something that has not been opened (#28). Does it still do an AccessViolation?

**Comment by Speykious** [comment]
I have no clue how I ended up putting the `isFormatContextOpen` line there... Man I'm tired

Anyways, thanks, will fix this.

Also, it occurred to me that your I/O Error might not be caused directly by the camera being busy.
Because when I try your exact code with my inactive virtual camera, I get this error message:
```
Cannot initialize camera: Device or resource busy
```
This tells me that FFmpeg can indeed return such an error message, and that for some reason that's not what it returned when you made your camera busy. It might be a bug inside of FFmpeg though...

**Comment by lubagov** [comment]
Are you testing the example under Windows? or used Linux? In general, I have the impression that the AccessViolation error in case the input is not open is a FFMPEG bug. In the FFMPEG code there are a lot of checks for NULL, in case the Context or something else NULL methods simply return and nothing bad happens. And it shouldn't be like that.

**Comment by Speykious** [comment]
> Are you testing the example under Windows? or used Linux? In general, I have the impression that the AccessViolation error in case the input is not open is a FFMPEG bug. In the FFMPEG code there are a lot of checks for NULL, in case the Context or something else NULL methods simply return and nothing bad happens. And it shouldn't be like that.

I only use Linux, no dual boot, and I haven't done that in a while... I would gladly have Windows on a secondary PC, but I want to personally avoid it on my main unit.

And yes, it might be an FFmpeg bug, in which case I can't do much tbh. :/
At least the AccessViolation will be gone by the next release of SeeShark.
